---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plugin-catalog
  name: plugin-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plugin-catalog
  template:
    metadata:
      labels:
        app: plugin-catalog
    spec:
      volumes:
      - name: plugin-cache
        emptyDir: {}
      initContainers:
      - image: k8s.gcr.io/git-sync/git-sync:v3.6.4
        name: git-sync-init
        volumeMounts:
          - name: plugin-cache
            mountPath: /data
        env:
          - name: GIT_SYNC_REPO
            valueFrom:
              secretKeyRef:
                name: git-auth-plugin-cache
                key: repository
                optional: false
          - name: GIT_SYNC_DEPTH
            value: "1"
          - name: GIT_SYNC_BRANCH
            value: "main"
          - name: GIT_SYNC_ROOT
            value: /data/git
          - name: GIT_SYNC_DEST
            value: "plugin-cache"
          - name: GIT_SYNC_PERIOD
            value: "20"
          - name: GIT_SYNC_ONE_TIME
            value: "true"
          - name: GIT_SYNC_USERNAME
            valueFrom:
              secretKeyRef:
                name: git-auth-plugin-cache
                key: user
                optional: false
          - name: GIT_SYNC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: git-auth-plugin-cache
                key: password
                optional: false
      containers:
      - image: k8s.gcr.io/git-sync/git-sync:v3.6.4
        name: git-sync
        volumeMounts:
          - name: plugin-cache
            mountPath: /data
        env:
          - name: GIT_SYNC_REPO
            valueFrom:
              secretKeyRef:
                name: git-auth-plugin-cache
                key: repository
                optional: false
          - name: GIT_SYNC_DEPTH
            value: "1"
          - name: GIT_SYNC_BRANCH
            value: "main"
          - name: GIT_SYNC_ROOT
            value: /data/git
          - name: GIT_SYNC_DEST
            value: "plugin-cache"
          - name: GIT_SYNC_PERIOD
            value: "20"
          - name: GIT_SYNC_ONE_TIME
            value: "false"
          - name: GIT_SYNC_USERNAME
            valueFrom:
              secretKeyRef:
                name: git-auth-plugin-cache
                key: user
                optional: false
          - name: GIT_SYNC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: git-auth-plugin-cache
                key: password
                optional: false
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - image: busybox
        name: cache-server
        args:
        - sh
        - -c
        - httpd -f -p 8280 -h /data/git/plugin-cache
        ports:
        - containerPort: 8280
        volumeMounts:
          - name: plugin-cache
            mountPath: /data
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
