---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: plugin-catalog
  name: plugin-catalog
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8280
  selector:
    app: plugin-catalog
  type: ClusterIP
